#    Craft Inc. Replicator
#    Copyright (C) 2013  Paul Schulze, Maximilian Häckel
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Craft Inc. Replicator
main: de.craftinc.replicator.Plugin
version: ${project.version}
softdepend: [Multiverse-Core]
authors: [ddidderr, beuth_el_max]
website: http://www.craftinc.de/craftinc-replicator


commands:
  replicate:
    description: Shows help for Craft Inc. Replicate

permissions:
  craftinc.replicator.update:
    default: op
    description: Allows to check for updates and also get notified on login if a new version is available.